[tools.go]
version = "latest"
postinstall = """
# LSP
go install golang.org/x/tools/gopls@latest
# Formatting
go install golang.org/x/tools/cmd/goimports@latest
# Find symbol information in Go source
go install github.com/rogpeppe/godef@latest
# Static analysis
go install honnef.co/go/tools/cmd/staticcheck@latest
# Debugger
go install github.com/go-delve/delve/cmd/dlv@latest
"""

[tools.golangci-lint]
version = "latest"
